"""empty message

Revision ID: 3c99d7be2967
Revises: 9acb0bf634c5
Create Date: 2016-11-04 13:19:08.255886

"""

# revision identifiers, used by Alembic.
revision = '3c99d7be2967'
down_revision = '9acb0bf634c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('comment', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'comment')
    ### end Alembic commands ###
